environment                        = "prod"
cost_center                        = "0000"
application_name                   = "myapp"
state_file_resource_group_name     = "myapp-statefile-rg"
state_file_resource_group_location = "Canada Central"
state_file_storage_account_name    = "myappstatefilesa"